apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: processador-pedidos
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: loja
        metrics_path: /metrics
        static_configs:
          - targets: ["loja:5000"]
      - job_name: painel
        metrics_path: /metrics
        static_configs:
          - targets: ["painel:3000"]
      - job_name: worker
        metrics_path: /metrics
        static_configs:
          - targets: ["worker:9100"]
